server {
  server_name pacmacro.sfucsss.org;

  location = /api/leader/ws {
      proxy_pass http://127.0.0.1:49152;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_read_timeout 86400s;
      proxy_send_timeout 86400s;
      proxy_buffering off;
      proxy_socket_keepalive on;
  }

  location = /api/admin/map/ws {
      proxy_pass http://127.0.0.1:49152;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      # One hour websocket timeout
      proxy_read_timeout 86400s;
      proxy_send_timeout 86400s;

      # Disables Nagle's algorithm for faster communication
      proxy_buffering off;

      # Nginx will close connections if the server has crashed
      proxy_socket_keepalive on;
  }

  location = /api/admin/ws {
      proxy_pass http://127.0.0.1:49152;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      # One hour websocket timeout
      proxy_read_timeout 86400s;
      proxy_send_timeout 86400s;

      # Disables Nagle's algorithm for faster communication
      proxy_buffering off;

      # Nginx will connections if the server has crashed
      proxy_socket_keepalive on;
  }

  location /api/ws/ {
    proxy_pass http://127.0.0.1:49152;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;

    # One hour websocket timeout
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;

    # Disables Nagle's algorithm for faster communication
    proxy_buffering off;

    # Nginx will connections if the server has crashed
    proxy_socket_keepalive on;
  }

  location /api/ {
    proxy_pass http://localhost:49152;
  }

  location / {
    root /var/www/html/pacmacro;
    try_files $uri $uri.html $uri/ =404;
  }
}
